# Generated by Django 2.0.13 on 2019-07-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='Activated',
            field=models.CharField(default='No', max_length=5),
        ),
    ]
