# Generated by Django 2.0.13 on 2019-07-17 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_newuser_activated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='Activated',
        ),
    ]
