# Generated by Django 2.0.13 on 2019-07-17 07:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_newuser_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='mail_sent_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='newuser',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
