# Generated by Django 2.0.13 on 2019-07-17 09:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_auto_20190717_1441'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewUser',
            new_name='user_details',
        ),
    ]
